Issue94 header only library
CachedNerds/Hatch pull request #110
Opened 2018-04-02 05:15 UTC by xmclark

This PR makes room for header-only libraries.

Most work in this PR is coercing the ProjectKind enum and eliminating the LibraryEnum to better express logic. The LibraryKind enum is not one that will be extended often, and it added some cognitive overhead. ProjectKind is now a copyable enum which and is the only enum needed for determing how to build assets.

The HeaderOnly variant is added. Header-only libraries do not need compilation, so no tup files should be generated. There is now a match on the ProjectKind before generating assets.

2018-04-02 05:19 UTC, xmclark commented
Beware! This PR fixes several different things that aren't all related...I recommend reviewing the individual commits instead of looking at all files changed.

I chose not to open separate PRs because I feel like all changes were directly required for implementing header-only support. The test and lint errors that were fixed are something we should have caught already, so I felt it appropriate to just fix them.

2018-04-21 08:25 UTC, DannyPeck requested changes
Looks good, there are a few questions.  Really like the enum cleanup!

2018-04-21 08:25 UTC, DannyPeck commented on hatch/src/cli/commands/new.rs
> +           .possible_values(&[BIN, STATIC, SHARED, &HEADER])
Does this need to be &HEADER? the others aren't.

2018-04-21 08:25 UTC, DannyPeck commented on hatch/src/assets/tests/generator.rs
> +      let _ = fs::remove_file("./test.test");
Fair enough.

2018-04-21 08:25 UTC, DannyPeck commented on hatch/src/assets/tupfile.rs
> +    Tupfile { kind: kind.clone() }
Much better.

2018-04-21 08:25 UTC, DannyPeck commented on hatch/src/cli/commands/new.rs
> +        ProjectKind::HeaderOnly => {
Perfect.

2018-04-21 08:25 UTC, DannyPeck commented on hatch/src/project/mod.rs
> +#[derive(Debug, Clone, Copy)]
👍

2018-06-23 19:26 UTC, xmclark commented
removed the Needs Review tag because a lot of this work inspired #112. We will need that merged before this can continue.

2018-06-27 16:04 UTC, xmclark commented
This PR has become very out-of-date. There is some header-only support, but it needs to be tested.

2018-06-27 16:04 UTC, closed without merging