Issue56 dep tests
CachedNerds/Hatch pull request #87
Opened 2018-02-02 16:28 UTC by technetos

Its up to us if we want to merge this in now or merge it in along with the refactor.  If we merge this in to dev now we will have a more concise history.  

The only reason its hasnt been merged yet is because of the missing tests for cloning but thats going to take longer than I would like.  

Implemented tests for the dependencies code.

2018-02-02 22:46 UTC, DannyPeck requested changes

2018-02-02 22:46 UTC, DannyPeck commented on hatch/src/deps/mod.rs
> +
Can we get rid of this extra new line?

2018-02-02 22:46 UTC, DannyPeck commented on hatch/src/deps/tests/clone_one_dep.rs
> +
Can we get rid of these new lines?

2018-02-02 22:46 UTC, DannyPeck commented on hatch/src/deps/tests/dependency.rs
> +  let dep =
This is weird, maybe put the string on a different line and then pass it in as a variable to conserve space?

2018-02-02 22:46 UTC, DannyPeck commented on hatch/src/deps/tests/dependency.rs
> +  let actual_url = "https://github.com/CachedNerds/TestProject.git";
Shouldn't this be the method call on dep?

2018-02-03 02:11 UTC, technetos commented on hatch/src/deps/tests/dependency.rs
> +  let actual_url = "https://github.com/CachedNerds/TestProject.git";
Yup! I fixed it in #88

2018-02-03 02:58 UTC, technetos commented
I have made the requested changes.

2018-02-03 20:01 UTC, closed without merging