issue85 task tests
CachedNerds/Hatch pull request #99
Opened 2018-02-15 10:03 UTC by DannyPeck

Added a success test for asset generation.

2018-02-15 23:04 UTC, xmclark requested changes

2018-02-15 23:04 UTC, xmclark commented on hatch/src/task/tests.rs
> +}
newline bruh

2018-02-17 02:40 UTC, technetos submitted a review, later dismissed

2018-02-18 06:21 UTC, xmclark approved these changes
well done, good sir 🎩

2018-02-18 17:51 UTC, technetos approved these changes

2018-02-18 17:53 UTC, xmclark approved these changes

2018-02-18 21:35 UTC, merged